# Generated by Django 4.2 on 2025-03-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Clients", "0002_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="treatment",
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="Treatment",
        ),
    ]
