# Generated by Django 4.2 on 2025-03-25 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Clients", "0003_remove_review_treatment_remove_review_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("Dermatologist", "Dermatologist"),
                            ("Plastic Surgeon", "Plastic Surgeon"),
                            ("Cosmetic Specialist", "Cosmetic Specialist"),
                            ("Licensed Professional", "Licensed Professional"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "credentials",
                    models.TextField(
                        help_text="List of professional qualifications and licenses."
                    ),
                ),
                ("experience_years", models.PositiveIntegerField(default=0)),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Short professional biography.", null=True
                    ),
                ),
                (
                    "available_days",
                    models.CharField(help_text="E.g., Monday-Friday", max_length=100),
                ),
                (
                    "working_hours",
                    models.CharField(
                        help_text="E.g., 9:00 AM - 5:00 PM", max_length=100
                    ),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("accepts_virtual_consultations", models.BooleanField(default=True)),
                ("accepts_in_person_consultations", models.BooleanField(default=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Admin approval for specialists."
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specialist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
