# Generated by Django 4.2 on 2025-03-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Clients", "0004_specialist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="specialist",
            name="user",
        ),
        migrations.DeleteModel(
            name="Consultation",
        ),
        migrations.DeleteModel(
            name="Specialist",
        ),
    ]
