# Generated by Django 4.2 on 2025-03-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Clients", "0005_remove_specialist_user_delete_consultation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[
                    ("client", "Client"),
                    ("specialist", "Specialist"),
                    ("admin", "Clinic Admin"),
                ],
                default="client",
                max_length=20,
            ),
        ),
    ]
