# Generated by Django 4.2 on 2025-03-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Clients", "0006_profile_role"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
