# Generated by Django 4.2 on 2025-03-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Clients", "0007_delete_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
