# Generated by Django 4.2 on 2025-03-26 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="specialist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specialist_consultations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
