# Generated by Django 4.2 on 2025-03-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0002_alter_consultation_specialist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="specialist",
            field=models.CharField(max_length=200),
        ),
    ]
