# Generated by Django 4.2 on 2025-03-29 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("specialists", "0002_specialist_is_active"),
        ("consultations", "0003_alter_consultation_specialist"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultation",
            name="room_name",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="specialist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="specialists.specialist"
            ),
        ),
    ]
