# Generated by Django 4.2 on 2025-03-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("specialists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="specialist",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
