# Generated by Django 4.2 on 2025-03-26 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("specialists", "0001_initial"),
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="specialist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="specialists.specialist"
            ),
        ),
    ]
